CREATE TABLE CARGO (
  MISDIRECTED BOOLEAN,
  UNLOADED_AT_DEST BOOLEAN,
  CALCULATED_AT DATETIME,
  CURRENT_VOYAGE_ID BIGINT,
  ETA DATETIME,
  ID BIGINT NOT NULL,
  LAST_EVENT_ID BIGINT,
  LAST_KNOWN_LOCATION_ID BIGINT,
  NEXT_EXPECTED_LOCATION_ID BIGINT,
  NEXT_EXPECTED_VOYAGE_ID BIGINT,
  ORIGIN_ID BIGINT,
  SPEC_ARRIVAL_DEADLINE DATETIME NOT NULL,
  SPEC_DESTINATION_ID BIGINT,
  SPEC_ORIGIN_ID BIGINT,
  NEXT_EXPECTED_HANDLING_EVENT_TYPE VARCHAR(255),
  ROUTING_STATUS VARCHAR(255),
  TRACKING_ID VARCHAR(255),
  TRANSPORT_STATUS VARCHAR(255),
  PRIMARY KEY (ID),
  FOREIGN KEY (CURRENT_VOYAGE_ID) REFERENCES VOYAGE(ID),
  FOREIGN KEY (LAST_EVENT_ID) REFERENCES HANDLING_EVENT(ID),
  FOREIGN KEY (LAST_KNOWN_LOCATION_ID) REFERENCES LOCATION(ID),
  FOREIGN KEY (NEXT_EXPECTED_LOCATION_ID) REFERENCES LOCATION(ID),
  FOREIGN KEY (NEXT_EXPECTED_VOYAGE_ID) REFERENCES VOYAGE(ID),
  FOREIGN KEY (ORIGIN_ID) REFERENCES LOCATION(ID),
  FOREIGN KEY (SPEC_DESTINATION_ID) REFERENCES LOCATION(ID),
  FOREIGN KEY (SPEC_ORIGIN_ID) REFERENCES LOCATION(ID)
);

CREATE TABLE CARRIER_MOVEMENT (
  ARRIVAL_LOCATION_ID BIGINT NOT NULL,
  ARRIVAL_TIME DATETIME NOT NULL,
  DEPARTURE_LOCATION_ID BIGINT NOT NULL,
  DEPARTURE_TIME DATETIME NOT NULL,
  ID BIGINT NOT NULL,
  VOYAGE_ID BIGINT,
  PRIMARY KEY (ID),
  FOREIGN KEY (VOYAGE_ID) REFERENCES VOYAGE(ID),
  FOREIGN KEY (DEPARTURE_LOCATION_ID) REFERENCES LOCATION(ID),
  FOREIGN KEY (ARRIVAL_LOCATION_ID) REFERENCES LOCATION(ID)
);

CREATE TABLE HANDLING_EVENT (
  CARGO_ID BIGINT,
  COMPLETION_TIME DATETIME,
  ID BIGINT NOT NULL,
  LOCATION_ID BIGINT,
  REGISTRATION_TIME DATETIME,
  VOYAGE_ID BIGINT,
  TYPE VARCHAR(255),
  PRIMARY KEY (ID),
  FOREIGN KEY (CARGO_ID) REFERENCES CARGO(ID),
  FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(ID),
  FOREIGN KEY (VOYAGE_ID) REFERENCES VOYAGE(ID)
);

CREATE TABLE LEG (
  CARGO_ID BIGINT,
  ID BIGINT NOT NULL,
  LOAD_LOCATION_ID BIGINT,
  LOAD_TIME DATETIME,
  UNLOAD_LOCATION_ID BIGINT,
  UNLOAD_TIME DATETIME,
  VOYAGE_ID BIGINT,
  PRIMARY KEY (ID),
  FOREIGN KEY (LOAD_LOCATION_ID) REFERENCES LOCATION(ID),
  FOREIGN KEY (UNLOAD_LOCATION_ID) REFERENCES LOCATION(ID),
  FOREIGN KEY (VOYAGE_ID) REFERENCES VOYAGE(ID),
  FOREIGN KEY (CARGO_ID) REFERENCES CARGO(ID)
);

CREATE TABLE LOCATION (
  ID BIGINT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  UNLOCODE VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE VOYAGE (
  ID BIGINT NOT NULL,
  VOYAGE_NUMBER VARCHAR(255),
  PRIMARY KEY (ID)
);

